ostis-ai/sc-component-manager

src/manager/commands/command_init/sc_component_manager_command_init.hpp

Fix bug when components init only for the last repository if there was more than one repository.

[init] Init components for all repositories

---

src/manager/commands/command_install/sc_component_manager_command_install.cpp
src/manager/commands/command_install/sc_component_manager_command_install.hpp
src/manager/utils/sc_component_utils.cpp
src/manager/utils/sc_component_utils.hpp

Move frequently used functions to componentUtils::SearchUtils
- GetComponentAddress
- GetComponentDependencies
- GetComponentInstallationMethod

[refactor][utils] Create utils for component manager

---

README.md
kb/specifications.scs

[docs] Update README example

---

COPYING.MIT
docs/changelog.md
docs/dev/CONTRIBUTING.md
docs/dev/codestyle.md
docs/dev/git-workflow.md
docs/license.md

Add changelog and license files

[docs] Add docs files

---

docs/changelog.md
src/manager/commands/command_install/sc_component_manager_command_install.cpp
src/manager/downloader/downloader_git.hpp
src/manager/downloader/downloader_handler.cpp
src/manager/sc-component-manager-factory/sc_component_manager_factory.cpp

[downloader] Remove trunk dir

---

.gitignore
README.md

docs: update README about installation, build and usage

---

docs/changelog.md
kb/types.scs
src/main.cpp
src/manager/commands/command_init/sc_component_manager_command_init.hpp
src/manager/commands/command_install/sc_component_manager_command_install.cpp
src/manager/commands/command_install/sc_component_manager_command_install.hpp
src/manager/commands/keynodes/ScComponentManagerKeynodes.cpp
src/manager/commands/keynodes/ScComponentManagerKeynodes.hpp
src/manager/commands/sc_component_manager_command_handler.hpp
src/manager/downloader/downloader_git.hpp
src/manager/downloader/downloader_handler.cpp
src/manager/downloader/downloader_handler.hpp
src/manager/sc-component-manager-factory/sc_component_manager_factory.cpp
src/manager/sc_component_manager.hpp
src/manager/sc_component_manager_impl.hpp

To test: 
Make section [sc-component-manager] in ostis-web-platform.ini file like 
```
knowledge_base_components_path = kb
problem_solver_components_path = problem-solver
interface_components_path = interface
```
Make specifications.scs for kb/ps/ui components like
<details>
<summary>That content</summary>
sc_component_manager_repository
<- concept_repository;
-> rrel_components_specifications: ..components_addresses;
-> rrel_repositories_specifications: ..repositories_addresses;;
..components_addresses
<- sc_node_tuple;
-> concept_cat_specification
(*
<- concept_reusable_component_specification;;
=> nrel_alternative_addresses:
...
(*
<- sc_node_tuple;;
<- singletone;;
-> rrel_1:
...
(*
-> [https://github.com/MksmOrlov/cat-kb-component]
(*
<- concept_github_url;;
*);;
*);;
*);;
*);
-> …

Install components to kb/interface/problem-solver directories

---

.github/workflows/style.yml
.gitignore
CMakeLists.txt
README.md
scripts/build_sc_component_manager.sh
scripts/formats.sh
scripts/run_sc_component_manager.sh
scripts/set_vars.sh
src/CMakeLists.txt
src/main.cpp
src/manager/commands/command_init/sc_component_manager_command_init.cpp
src/manager/commands/command_init/sc_component_manager_command_init.hpp
src/manager/commands/command_install/sc_component_manager_command_install.cpp
src/manager/commands/command_install/sc_component_manager_command_install.hpp
src/manager/commands/command_search/sc_component_manager_command_search.cpp
src/manager/commands/command_search/sc_component_manager_command_search.hpp
src/manager/commands/sc_component_manager_command_handler.hpp
src/manager/commands/url_parser/repository_url_parser.hpp
src/manager/downloader/downloader_git.hpp
src/manager/downloader/downloader_handler.cpp
src/manager/downloader/downloader_handler.hpp
src/manager/sc-component-manager-factory/sc_component_manager_factory.cpp
src/manager/sc-component-manager-factory/sc_component_manager_factory.hpp
src/manager/sc_component_manager.cpp
src/manager/sc_component_manager.hpp
src/manager/sc_component_manager_impl.hpp
src/manager/utils/sc_component_utils.cpp

CI will be fixed after platform update

feat: connect component manager to platform

---

scripts/run_sc_component_manager.sh

fix: run script with i flag

---

src/manager/downloader/downloader_git.hpp

[downloader] Install whole component from repository

---

src/manager/downloader/downloader_git.hpp
src/manager/sc_component_manager.cpp

[downloader] Divide fillExistingComponents method into 2

---

src/CMakeLists.txt

[build] macos

---

src/manager/commands/command_install/sc_component_manager_command_install.cpp
src/manager/downloader/downloader_git.hpp
src/manager/utils/sc_component_utils.cpp

To test change link in _ostis-web-platform-components-specification.scs_ on
`https://github.com/MakarenkoAI/sc-web`
Then 
`components init`
`components install --idtf sc_web`

[fix][downloader]: Download sc-web

---

.gitmodules
CMakeLists.txt
README.md
src/manager/command_parser/sc_component_manager_command_parser.hpp
src/manager/commands/constants/command_constants.cpp
src/manager/commands/constants/command_constants.hpp
tests/units/sc_component_manager_test.hpp
tests/units/test_command_parser.cpp
tests/units/test_url_parser.cpp
thirdparty/CMakeLists.txt
thirdparty/gtest.cmake

components install, все качаем
components install --idtf sc_web качаем sc_web
components install sc_web  качаем sc_web

[fix] Flag --idtf

---

docs/changelog.md
src/manager/command_parser/sc_component_manager_command_parser.hpp
src/manager/commands/command_search/sc_component_manager_command_search.cpp
tests/units/test_command_parser.cpp

components search --explanation SC 
components search --explanation
components search --explanation "SC"

[search] Flag --explanation with empty value

---

kb/specifications.scs
src/manager/commands/command_install/sc_component_manager_command_install.cpp
src/manager/commands/constants/command_constants.cpp
src/manager/commands/constants/command_constants.hpp
src/manager/utils/sc_component_utils.cpp
src/manager/utils/sc_component_utils.hpp

To test: make init, search, install, search and see that there is no duplications

[install] Resolve multiple specification loading

---

CMakeLists.txt
dependencies.cmake
src/CMakeLists.txt
src/manager/agents/CMakeLists.txt
src/manager/agents/common-module/CMakeLists.txt
src/manager/agents/init-module/CMakeLists.txt
src/manager/agents/install-module/CMakeLists.txt
src/manager/agents/search-module/CMakeLists.txt
src/manager/console-interface/CMakeLists.txt
tests/tests.cmake

Dependency:
- https://github.com/ostis-ai/sc-machine/pull/375

[cmake] Optimize dependencies with sc-machine

---

src/manager/agents/common-module/CMakeLists.txt

Fix build on macOS

---

src/manager/agents/common-module/CMakeLists.txt

[cmake] Link with sc-config-utils for macOS

---

kb/specifications.scs

Все компоненты лежат тут https://github.com/MksmOrlov/ostis-kb-lib

[kb] Add new components specification

---

kb/specifications.scs

[kb] Update specifications

---

kb/specifications.scs
src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
src/manager/agents/search-module/utils/sc_component_manager_command_search.hpp

[search] Use ScAddr instead of system identifiers

---

.github/workflows/style.yml
docs/changelog.md
src/manager/agents/common-module/downloader/downloader_git.hpp
src/manager/agents/install-module/utils/sc_component_manager_command_install.cpp
src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
src/manager/console-interface/sc_component_manager.cpp
src/manager/console-interface/sc_component_manager.hpp
src/module/sc_component_manager_module.cpp

[interface] Check pool for new strings; join thread with getline

---

docs/changelog.md
docs/images/gwf/agents.gwf
src/manager/agents/init-module/module/agents/sc_component_manager_agent_init.hpp
src/manager/agents/install-module/module/agents/sc_component_manager_agent_install.hpp
src/manager/agents/install-module/utils/sc_component_manager_command_install.cpp
src/manager/agents/search-module/module/agents/sc_component_manager_agent_search.hpp
src/manager/console-interface/sc_component_manager_command_handler.hpp
tests/testStructures/action_components_init.scs
tests/testStructures/action_components_install.scs
tests/testStructures/action_components_search.scs
tests/units/agent_tests.cpp

[refactor] Rename questions to actions

---

src/manager/agents/common-module/commands/sc_component_manager_command.hpp
src/manager/agents/common-module/module/utils/common_utils.hpp
src/manager/agents/init-module/module/agents/sc_component_manager_agent_init.hpp
src/manager/agents/install-module/module/agents/sc_component_manager_agent_install.hpp
src/manager/agents/search-module/module/agents/sc_component_manager_agent_search.hpp

[refactor] Use ScAddrHashFunc without argument

---

kb/types.scs
src/manager/agents/common-module/module/keynodes/ScComponentManagerKeynodes.hpp

refactor: rename norole to non_role

---

src/module/sc_component_manager_module.cpp

[fix] Add sc-config in module
